CREATE SCHEMA dpa-reports;

USE dpa-reports;

CREATE TABLE `Account_Information_Master` (
  `Application_Page_ID` bigint(20) NOT NULL DEFAULT '0',
  `Business_Manager_Ad_Account_ID` bigint(20) DEFAULT '0',
  `Business_Client_Name` varchar(45) DEFAULT NULL,
  `Application_Long_Lived_Access_Token` longtext,
  PRIMARY KEY (`Application_Page_ID`)
);

CREATE TABLE `Account_Email_List` (
  `Email_ID` varchar(45) NOT NULL,
  `Client_ID` bigint(45) DEFAULT NULL,
  `Client_Name` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`Email_ID`),
  KEY `Email_Page_ID_idx` (`Client_ID`),
  KEY `DPAEmail_Page_ID_idx` (`Client_ID`),
  CONSTRAINT `DPAEmail_Clinet_Page_Id` FOREIGN KEY (`Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `ActionTypes_AdGroup_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_AdGroup_ID` bigint(20) DEFAULT NULL,
  `Application_AdGroup_Name` varchar(200) DEFAULT NULL,
  `Client_Reports_Action_Type` varchar(200) DEFAULT NULL,
  `Client_Reports_Value` int(11) DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  KEY `ActionTypes_Adgroup_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `ActionTypes_Adgroup_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `ActionTypes_AdSet_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_AdSet_ID` bigint(20) DEFAULT NULL,
  `Application_AdSet_Name` varchar(200) DEFAULT NULL,
  `Client_Reports_Action_Type` varchar(200) DEFAULT NULL,
  `Client_Reports_Value` int(11) DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  KEY `ActionTypes_AdSet_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `ActionTypes_AdSet_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `ActionTypes_Campaign_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Campaign_ID` bigint(20) DEFAULT NULL,
  `Application_Campaign_Name` varchar(200) DEFAULT NULL,
  `Client_Reports_Action_Type` varchar(200) DEFAULT NULL,
  `Client_Reports_Value` int(11) DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  KEY `ActionTypes_Campaign_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `ActionTypes_Campaign_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `ActionTypes_AdAccount_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_AdAccount_ID` bigint(20) DEFAULT NULL,
  `Application_AdAccount_Name` varchar(200) DEFAULT NULL,
  `Client_Reports_Action_Type` varchar(200) DEFAULT NULL,
  `Client_Reports_Value` int(11) DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  KEY `ActionTypes_AdAccount_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `ActionTypes_AdAccount_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Aggregated_Account_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Ad_Account_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_Account_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Aggregated_Account_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Aggregated_Account_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Aggregated_AdSet_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Ad_AdSet_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_AdSet_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Aggregated_AdSet_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Aggregated_AdSet_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Aggregated_Ad_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Ad_Group_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_Group_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  `Client_Ad_Relevance_Score` double DEFAULT NULL,
  KEY `Aggregated_Adgroup_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Aggregated_Adgroup_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Aggregated_Campaign_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Campaign_ID` bigint(20) DEFAULT NULL,
  `Application_Campaign_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Aggregated_Campaign_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Aggregated_Campaign_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `CountryLevel_AdAccount_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Ad_Account_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_Account_Name` varchar(45) DEFAULT NULL,
  `Country` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `country_page_id_idx` (`Application_Client_ID`),
  CONSTRAINT `country_account_page_id` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `CountryLevel_AdGroup_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_AdGroup_ID` bigint(20) DEFAULT NULL,
  `Application_AdGroup_Name` varchar(45) DEFAULT NULL,
  `Country` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  `Client_Ad_Relevance_Score` double DEFAULT NULL,
  KEY `page_id_idx` (`Application_Client_ID`),
  KEY `country_adgroup_page_id_idx` (`Application_Client_ID`),
  CONSTRAINT `country_page_id_adgroup` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `CountryLevel_AdSet_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_AdSet_ID` bigint(20) DEFAULT NULL,
  `Application_AdSet_Name` varchar(45) DEFAULT NULL,
  `Country` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Country_AdSet_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Country_AdSet_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `CountryLevel_Campaign_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Campaign_ID` bigint(20) DEFAULT NULL,
  `Application_Campaign_Name` varchar(45) DEFAULT NULL,
  `Country` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Country_Campaign_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Country_Campaign_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Overall_Account_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Ad_Account_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_Account_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Age_Stats_Range` varchar(45) DEFAULT NULL,
  `Client_Reports_Gender_Stats` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Overall_Account_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Overall_Account_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Overall_AdSet_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Ad_AdSet_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_AdSet_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Age_Stats_Range` varchar(45) DEFAULT NULL,
  `Client_Reports_Gender_Stats` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Overall_AdSet_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Overall_AdSet_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Overall_Ad_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Ad_Group_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_Group_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Age_Stats_Range` varchar(45) DEFAULT NULL,
  `Client_Reports_Gender_Stats` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  `Client_Ad_Relevance_Score` double DEFAULT NULL,
  KEY `Overall_Adgroup_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Overall_Adgroup_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Overall_Campaign_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Campaign_ID` bigint(20) DEFAULT NULL,
  `Application_Campaign_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Age_Stats_Range` varchar(45) DEFAULT NULL,
  `Client_Reports_Gender_Stats` varchar(45) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Overall_Campaign_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Overall_Campaign_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `PlacementLevel_AdAccount_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Ad_Account_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_Account_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Placement` varchar(200) DEFAULT NULL,
  `Client_Reports_Impression_Device` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Placement_AdAccount_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Placement_AdAccount_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `PlacementLevel_AdGroup_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_AdGroup_ID` bigint(20) DEFAULT NULL,
  `Application_AdGroup_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Placement` varchar(200) DEFAULT NULL,
  `Client_Reports_Impression_Device` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  `Client_Ad_Relevance_Score` double DEFAULT NULL,
  KEY `Placement_AdGroup_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Placement_AdGroup_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `PlacementLevel_AdSet_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_AdSet_ID` bigint(20) DEFAULT NULL,
  `Application_AdSet_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Placement` varchar(200) DEFAULT NULL,
  `Client_Reports_Impression_Device` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Placement_AdSet_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Placement_AdSet_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `PlacementLevel_Campaign_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Campaign_ID` bigint(20) DEFAULT NULL,
  `Application_Campaign_Name` varchar(45) DEFAULT NULL,
  `Client_Reports_Placement` varchar(200) DEFAULT NULL,
  `Client_Reports_Impression_Device` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Placement_Campaign_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Placement_Campaign_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Product_Account_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_Account_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_Account_Name` varchar(45) DEFAULT NULL,
  `Client_Product_ID` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  KEY `Product_Account_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Product_Account_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Product_AdSet_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT NULL,
  `Client_AdSet_ID` bigint(20) DEFAULT NULL,
  `Client_AdSet_Name` varchar(45) DEFAULT NULL,
  `Client_Product_ID` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  KEY `Product_Adest_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Product_Adest_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Product_Ad_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT NULL,
  `Client_Ad_Group_ID` bigint(20) DEFAULT NULL,
  `Client_Ad_Group_Name` varchar(45) DEFAULT NULL,
  `Client_Product_ID` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Relevancy_Score` double DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  KEY `Product_Ad_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Product_Ad_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `Product_Campaign_Statistics_Results` (
  `Application_Client_ID` bigint(200) DEFAULT NULL,
  `Client_Campaign_ID` bigint(20) DEFAULT NULL,
  `Client_Campaign_Name` varchar(45) DEFAULT NULL,
  `Client_Product_ID` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  KEY `Product_Campaign_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Product_Campaign_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `RegionLevel_AdAccount_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Ad_Account_ID` bigint(20) DEFAULT NULL,
  `Application_Ad_Account_Name` varchar(45) DEFAULT NULL,
  `Region` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Region_AdAccount_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Region_AdAccount_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `RegionLevel_AdGroup_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_AdGroup_ID` bigint(20) DEFAULT NULL,
  `Application_AdGroup_Name` varchar(45) DEFAULT NULL,
  `Region` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  `Client_Ad_Relevance_Score` double DEFAULT NULL,
  KEY `Region_AdGroup_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Region_AdGroup_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `RegionLevel_AdSet_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_AdSet_ID` bigint(20) DEFAULT NULL,
  `Application_AdSet_Name` varchar(45) DEFAULT NULL,
  `Region` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Region_AdSet_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Region_AdSet_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE `RegionLevel_Campaign_Statistics_Results` (
  `Application_Client_ID` bigint(20) DEFAULT '0',
  `Application_Campaign_ID` bigint(20) DEFAULT NULL,
  `Application_Campaign_Name` varchar(45) DEFAULT NULL,
  `Region` varchar(200) DEFAULT NULL,
  `Client_Reports_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Frequency` double DEFAULT NULL,
  `Client_Reports_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Clicks` int(11) DEFAULT NULL,
  `Client_Reports_Total_Actions` int(11) DEFAULT NULL,
  `Client_Reports_Social_Reach` int(11) DEFAULT NULL,
  `Client_Reports_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_Unique_Social_Impressions` int(11) DEFAULT NULL,
  `Client_Reports_CPM` double DEFAULT NULL,
  `Client_Reports_CPP` double DEFAULT NULL,
  `Client_Reports_CPC` double DEFAULT NULL,
  `Client_Reports_CTR` double DEFAULT NULL,
  `Client_Reports_Spend` double DEFAULT NULL,
  `Stats_Date` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_Start` datetime DEFAULT NULL,
  `Client_Reports_Ad_Activity_Date_End` datetime DEFAULT NULL,
  `Client_Cost_Per_Unique_Click` double DEFAULT NULL,
  KEY `Region_Campaign_Page_ID_idx` (`Application_Client_ID`),
  CONSTRAINT `Region_Campaign_Page_ID` FOREIGN KEY (`Application_Client_ID`) REFERENCES `Account_Information_Master` (`Application_Page_ID`) ON DELETE NO ACTION ON UPDATE CASCADE
);
